
Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the Application Load Balancer should be deployed to

    InternalLoadBalancerUrl:
        Type: String
        Description: Amazon given Internal LB URL		

Resources:


    ##RecordSet for internal load balancer
    RecordSet:
        Type: "AWS::Route53::RecordSet"
        Properties: 
             AliasTarget: !Ref InternalLoadBalancerUrl
             Comment: "Internal ALB"
             HostedZoneId: !Ref HostedZone
             Name: ilb.wp.com
             Region: !Ref "AWS::Region"
             Type: CNAME 